server:
  port: 8989
  servlet:
    context-path: /man
mybatis-plus:
  # mp配置
  type-aliases-package: cn.chenmanman.manmoviebackend.domain.entity
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
  global-config:
    db-config:
      id-type: auto
spring:
  # mysql数据源配置
  datasource:
    username: root
    password: huanyuan
    url: jdbc:mysql://localhost:3306/man_movie?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
logging:
  config: classpath:log4j2.xml
knife4j:
  enable: true
  openapi:
    title: 慢慢视频站api文档
    description: "慢慢视频站api文档"
    email: 1738352551@qq.com
    concat: 陈慢慢
    url: https://docs.xiaominfo.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: movie
        api-rule: package
        api-rule-resources:
          - cn.chenmanman.manmoviebackend.controller
#alibaba:
#  endpoint: oss-cn-beijing.aliyuncs.com
#  accessKeyId: ********
#  accessKeySecret: ********
